### ISSUE TITLE
Exception: get_class() expects parameter 1 to be object, null given

### ISSUE THREAD

**Issue by jpagarcia** [barryvdh/laravel-ide-helper#1028]
I just installed the package and tried to generate the docs and I'm encountering this issue, I'm not sure what to check. I looked up current issues and found this [#208 - comment](https://github.com/barryvdh/laravel-ide-helper/issues/208#issuecomment-649570555)  that mentioned a similar issue but didn't mention any fix for it. 

![image](https://user-images.githubusercontent.com/2853613/91672046-5abcd780-eb5e-11ea-8696-068a17f5ef43.png)

**Comment by mfn** [comment]
> but didn't mention any fix for it

Because the OP never gave any feedback, but granted: it was a long time ago…

The referenced comment contains already lots of pointers: are you using aliases too? might there be wrong classes?

It would help if you could some debugging, I suspect the error gets caught in `\Barryvdh\LaravelIdeHelper\Alias::detectRoot`

**Comment by jpagarcia** [comment]
I'm not sure, I'll get back to you once I've checked. Thanks!

**Comment by jpagarcia** [comment]
Closing ticket. Not necessary anymore for my needs.
