### ISSUE TITLE
Suggestion: Remove TODOs

### ISSUE THREAD

**Issue by RJFares** [barryvdh/laravel-ide-helper#1077]
The _ide_helper.php has @todo lines which are flagged in my IDE as todos for my projects.
Would it be possible to not publish those lines?

**Comment by mfn** [comment]
Which IDE exactly? How this the flagging appear / disrupts the workflow specifically?

Some steps/screenshots would be useful.

Thanks

**Comment by RJFares** [comment]
The TODO items of libraries usually remain inside their vendor folders where they should be.
The generated _ide_helper.php is inside the project structure, outside of the vendor folder, so the todo items appear as if they belong to the project itself.
Admittedly this is a minor issue, but if every vendor wants to add his todo as such, there were would be a lot of clutter, in my humble opinion at least.

Feel free to close the issue if needed, this is just a suggestion.

**Comment by mfn** [comment]
> Feel free to close the issue if needed, this is just a suggestion.

I actually would like to dig into a this, but you have not provide any of the information I asked for. Basically: I'm using PhpStorm and don't experience this problem, and if you do, I'd like to take a closer look (no promises though 🤞 )

**Comment by RJFares** [comment]
My apologies I was focusing more on the concept of vendor todos in general and was pondering on whether generated files outside of vendor dir should have todos.
I'm using PHPStorm also. So in the TODO tab, you can see the todos of the generated _ide_helper.php. Would those items be beneficial to users of the lib?

**Comment by mfn** [comment]
Got it!

Never used the TODO tab 😄 , insightful.

I think the phpdoc are  more or less faithful copypaste of the original source and you do end up there if you "go to definition", so it's helpful to have the original there.

OTOH this would be a non-issue if PhpStorm would allow to simply have the ability to ignore TODOs, but I don't see a "per directory"-setting or similar. 

There is a "TODO comment" inspection, seems to be disabled by default:
![image](https://user-images.githubusercontent.com/87493/95551263-ba828a00-0a0a-11eb-9ca9-3f3c32361d30.png)

I'm pointing this out because it supports "scopes" which would be the equivalent of the per-dir setting I just mentioned.

But I also just realized, there _is a_ "Scope Based" approach possible: did you try this?
![image](https://user-images.githubusercontent.com/87493/95551362-f158a000-0a0a-11eb-99c6-28131293dccd.png)

**Comment by RJFares** [comment]
That's true :)
Usually, we scope to project/non-vendor & non-generated & no-cache files.
Since PHPStorm does not support ignoring, the other way is to add a specific exclusion to that _ide_helper.php through the scope above.
So we go back to the original issue: if we have multiple vendors who do this, then we'd have to manually add an exclusion rule to each of our projects targeting each vendor file that is outside of "vendor".
Just something to think about ^^

**Comment by mfn** [comment]
I think adding more complexity to the ide-helper for this, which is very easily fixed in the IDE, isn't really warranted.

The next person then comes along complaining the phpdocs don't match the original one.

Then we end up with a config for that also.

💥 

😄 

> Feel free to close the issue if needed, this is just a suggestion.

IMHO: it was proven the IDE is very well capable handling this and given that this issue never came up before despite ide_helper.php being a long time generated like this I don't think there's much actionable we should do here.

**Comment by RJFares** [comment]
Back to scoping then :)
Thanks
