### ISSUE TITLE
MySQL decimal casting

### ISSUE THREAD

**Issue by molbal** [barryvdh/laravel-ide-helper#1154]
### Versions:
- ide-helper Version: 2.9.0
- Laravel Version: 8.26.1
- PHP Version:8.0.1

### Question:
MySQL's decimal field is being cast into string - is there a toggle/config entry to use float instead?

**Comment by mfn** [comment]
Someone may correct me (I don't use MySQL), but I think this is intentional: the `DECIMAL` type is a "fixed point" type and PHP only has "floating point" types. I.e. a conversion to float **can be lossy**.

IMHO the correct fix is to simply add a getter in your model if you're sure you never lose data.

**Comment by molbal** [comment]
That is absolutely true. It can very easily become messy unless we absolutely know what we are doing. Getters are a good workaround, cheers.

**Comment by mfn** [comment]
Great!

> and PHP only has "floating point" type

Just to correct myself, of course there is https://www.php.net/manual/en/book.bc.php but I don't think we should do this autmagically: also this would require an extension dependency and feels also better done within the models getter.

**Comment by molbal** [comment]
Yup, that's definitely out of scope for this package.  I think I'll just use brick/math as I can easily use it within getters.
Thank you again
