### ISSUE TITLE
Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found on shared hosting

### ISSUE THREAD

**Issue by pvdochtend** [barryvdh/laravel-ide-helper#1169]
### Versions:
- ide-helper Version: 2.6
- Laravel Version: 6.0
- PHP Version: 7.4.14

### Description:

I have a problem with deploying my Laravel site to a (shared) hosted environment.

1) I use git-ftp to upload the files from our git to the remote server.
2) Copy the .env file with all the settings (APP_ENV-production, database etc)
3) When running "composer update --no-dev" I receive the error:

"Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found"

I can't run NPM on the server because it's not available (shared server).

I don't know which logging can help for this error, so please let me know I can add it very fast.

**Comment by scwall** [comment]
i have same problem :/

**Comment by pvdochtend** [comment]
I've read almost the whole internet about Laravel and deployments :)

On the Laravel site they only suggest the standard commands:

`composer update
php artisan migrate
php artisan config:clear
php artisan key:generate
composer dump-autoload`

To solve this issue a lot of threads are saying:
`npm install
npm run dev (or npm run prod)`

But as I was saying I can't run this on the shared hosting.

Is the solution to do the npm install on a client (or docker image in the pipeline) and upload the results to the shred hosting?
I don't know yet. I wll go to test that. Although I don't know if I can upload the **result** of the build to the shared hosting and respecting the git ignore and uploading only the changes in the files :D... If someone has a fast solution to solve this issue. Please let me know!

**Comment by mfn** [comment]
> I use git-ftp to upload the files from our git to the remote server.

- did you upload `bootstrap/cache/*.php`?
- does it contain references to ide-helper?
  Output of `grep -l IdeHelper bootstrap/cache/*` can be
  ```
  bootstrap/cache/packages.php
  bootstrap/cache/services.php
  ```

If both answers are "yes", than that's the problem: you must not upload those cache files.

If not, do you have a full stacktrace?

PS: I doubt `npm` is involved in this, looks like a red herring to me.

**Comment by pvdochtend** [comment]
Thank you very much for the fast response. I checked the cache folder... There was only the packages.php but no line mentioning Idehelper. But I removed it to be sure..

The complete output (error) is:

` composer update --no-dev
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file
Package operations: 0 installs, 0 updates, 46 removals
  - Removing webmozart/assert (1.10.0)
  - Removing theseer/tokenizer (1.2.0)
  - Removing symfony/filesystem (v5.2.4)
  - Removing seld/phar-utils (1.1.1)
  - Removing seld/jsonlint (1.8.3)
  - Removing sebastian/version (2.0.1)
  - Removing sebastian/type (1.1.4)
  - Removing sebastian/resource-operations (2.0.2)
  - Removing sebastian/recursion-context (3.0.1)
  - Removing sebastian/object-reflector (1.1.2)
  - Removing sebastian/object-enumerator (3.0.4)
  - Removing sebastian/global-state (3.0.1)
  - Removing sebastian/exporter (3.1.3)
  - Removing sebastian/environment (4.2.4)
  - Removing sebastian/diff (3.0.3)
  - Removing sebastian/comparator (3.0.3)
  - Removing sebastian/code-unit-reverse-lookup (1.0.2)
  - Removing react/promise (v2.8.0)
  - Removing phpunit/phpunit (8.5.14)
  - Removing phpunit/php-token-stream (4.0.4)
  - Removing phpunit/php-timer (2.1.3)
  - Removing phpunit/php-text-template (1.2.1)
  - Removing phpunit/php-file-iterator (2.0.3)
  - Removing phpunit/php-code-coverage (7.0.14)
  - Removing phpspec/prophecy (1.12.2)
  - Removing phpdocumentor/type-resolver (1.4.0)
  - Removing phpdocumentor/reflection-docblock (5.2.2)
  - Removing phpdocumentor/reflection-common (2.2.0)
  - Removing phar-io/version (3.1.0)
  - Removing phar-io/manifest (2.0.1)
  - Removing nunomaduro/collision (v3.2.0)
  - Removing myclabs/deep-copy (1.10.2)
  - Removing mockery/mockery (1.4.3)
  - Removing maximebf/debugbar (v1.16.5)
  - Removing justinrainbow/json-schema (5.2.10)
  - Removing hamcrest/hamcrest-php (v2.0.1)
  - Removing fzaninotto/faker (v1.9.2)
  - Removing filp/whoops (2.9.2)
  - Removing doctrine/instantiator (1.4.0)
  - Removing composer/xdebug-handler (1.4.5)
  - Removing composer/spdx-licenses (1.5.5)
  - Removing composer/semver (3.2.4)
  - Removing composer/composer (2.0.11)
  - Removing barryvdh/reflection-docblock (v2.0.6)
  - Removing barryvdh/laravel-ide-helper (v2.8.2)
  - Removing barryvdh/laravel-debugbar (v3.5.2)
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Class App\Exceptions\ApiOperationFailedException located in ./app/Console/ApiOperationFailedException.php does not comply with psr-4 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In ProviderRepository.php line 208:

  Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
`

**Comment by pbgswd** [comment]
OK had this problem Here is how it happened:
I am close to launching the site. I am looking at the laravel deployment page, it says to run this:

`composer install --optimize-autoloader --no-dev`

So I ran it, I get an error pertaining to the this package.
I think, oh well, I can just remove the package by way of 

`composer remove laravel-ide-helper`

but at the end of that is when I got the error:

`> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In ProviderRepository.php line 208:
                                                                        
Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found`

What happens with `composer remove packagename` is that the package is removed from composer.json and not much more. 

Laravel may have written in the path of the vendor package into several files by this time. I did find it in config/app.php but grepping for the package revealed it in several places, in fact more places than I could deal with. So I just nuked the instance, cloned it back, and then made the changed to remove the file in config.json and config/app.php to not have this package in my application. 

 My original need to use optimize-autoloader was resolved by all this. 

Unfortunately, this is a problem I have run into with another unrelated composer package. 

You should not have to suddenly dive in to the internals of the application to remove a composer package. That is usually the layer that is below what you are working on, that you generally never look at. This should not happen ideally, but this is what happens. 

I was fortunate to resolve this problem in my own way, but others may not have the option to easily resolve it. 

A vendor package should be able to be removed as easily as it is to install (in a perfect world). 

But this package isnt the only one out there that can cause such an issue. 

It was way easier to clone in and set up a new instance than it was to attempt the surgery to remove all the references. If there is a way to deal with it, I dont know it. 

You should be sure you want or need the package before you install it. You should have multiple instances of your project checked out just so you can work out unexpected issues.

**Comment by pvdochtend** [comment]
As described above. It was stated in the section Providers / Package Service Providers of the /config/app.php file.

When I comment out that line. Composer is going ok.

No I have to tackle the "The Mix manifest does not exists" error in LAravel (That was the error where NPM was needed :(

**Comment by pbgswd** [comment]
It appears that we had a similar or same problem doing different things. 
I dont know if my comments were helpful to you but I think that looking at issues from different perspectives sometimes can shed light on what you are dealing with.

**Comment by joris-Bourguet** [comment]
If someone still have the issue. Try to remove in config.app the `Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class,` line

This issue happen when you install the package only for dev and do `composer install --optimize-autoloader --no-dev` for produ ction. The package isn't installed anymore and app.php return this error `Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found`

**Comment by AforDesign** [comment]
Also check:
bootstrap/app.php
bootstrap/providers.php

To my surpirse, my IDE (PHPStorm) skips files in the bootstrap directory by default when searching the entire project.
It does find the searched string when executed on the directory itself.

In my case the service provider was loaded in app.php within the  ->withProviders([ ... ]) array.
It was propably moved there by using the Laravel upgrade services form v9-10 or v10-11.
But since Laravel 11 changed how serivce providers are loaded, it is not needed to manually load it anymore.
