### ISSUE TITLE
Auto complete not working (PhpStorm 8.01) 

### ISSUE THREAD

**Issue by slickorange** [barryvdh/laravel-ide-helper#128]
I am using Laravel 4.2 and PhpStorm 8.01.

I have tried using a generated _ide_helper file as well as the pre-generated one you provide. Auto complete refuses to work for Facades and Models.. I have tried everything I can think of. 

UPDATE:
It is working for my models now, but still not for other facades like Input, Redirect, View etc..

Any ideas?

**Comment by Kussie** [comment]
I'm getting the same issue in 8.0.2 now.  Auto completion on my models is mostly working.  But for the Laravel facades it doesn't seem to be working, like Response.  When i do Response:: (With Use Response at the top of my controller since all of mine are namespaced) the only suggestion i get is an option called "class", i get the exact same thing using \Response::
