### ISSUE TITLE
ide-helper always generate id types of int even if string.

### ISSUE THREAD

**Issue by letuss004** [barryvdh/laravel-ide-helper#1283]
### Versions:
- ide-helper Version:  2.10.0
- Laravel Version: 8.7 
- PHP Version: 8

### Description:
My "users" table has string('id') as primary key but ide-helper always generate id types of int. 

### Steps To Reproduce:
1. Change "user" table id from id to string
2. Use ide-helper:models

![image](https://user-images.githubusercontent.com/74813352/145826861-36ee2d7e-e44b-44b2-84a6-1e1f88c27244.png)
![image](https://user-images.githubusercontent.com/74813352/145826915-f3eb75ee-63c6-494f-8fce-a576f1addf10.png)

**Comment by lwinmaungmaung** [comment]
Me also the same, +1

**Comment by hrapeichuk** [comment]
I also managed to reproduce this problem. Generally there is no problem, it's expected behavior for Laravel. The `Model` abstract class defined primary key type as `int`:
```php
/**
 * The "type" of the primary key ID.
 *
 * @var string
 */
protected $keyType = 'int';
```
Source: https://github.com/illuminate/database/blob/master/Eloquent/Model.php#L63

As it's written in Laravel documentation, if you use other type for `id` you should redefine `$keyType` property on your model, like this:
```php
protected $keyType = 'string';
```
Source: https://laravel.com/docs/8.x/eloquent#primary-keys

I think this issue can be closed.

**Comment by mfn** [comment]
> I think this issue can be closed.

Following the suggestion as OP hasn't come back in a month
