### ISSUE TITLE
Too few arguments to function Illuminate\Console\GeneratorCommand::__construct(), 0 passed

### ISSUE THREAD

**Issue by JunaidQadirB** [barryvdh/laravel-ide-helper#1286]
### Versions:
- ide-helper Version: 2.10.0
- Laravel Version: 8.75.0
- PHP Version:7.4.26
-  jq/cray Version: 3.2.0-beta3

### Description:

I'm the maintainer of a package called [Cray](https://github.com/JunaidQadirB/cray).
When this package is installed, `ide-helper` would throw this error:
```
Too few arguments to function Illuminate\Console\GeneratorCommand::__construct(), 0 passed in /var/www/uot-web.test/vendor/jq/cray/src/CrayServiceProvider.php on line 82 and exactly 1 expected
```

Since `Cray` extends its own version of `GeneratorCommand` which in turn extends `\Illuminate\Console\GeneratorCommand`.
The tool works well otherwise, but when I run `php artisan ide-helper:generate`, it throws this exception.

I've opened [an issue ](https://github.com/JunaidQadirB/cray/issues/2) on my project as well.

### Steps To Reproduce:

- Install `ide-helper`
- Install `jq/cray`
- Run 
```bash
php artisan ide-helper:generate
```

**Comment by mfn** [comment]
@JunaidQadirB your instantiation of your Cray command is wrong
```php
        // Register the main class to use with the facade
        $this->app->singleton('cray', function () {
            return new Cray();
        });
```
it aborts on the line `new Cray()`, `Cray` extends from `\JunaidQadirB\Cray\Console\Contracts\GeneratorCommand` which extends from `\Illuminate\Console\GeneratorCommand` which has this constructor definition:
```php
    public function __construct(Filesystem $files)
    {
        parent::__construct();

        if (in_array(CreatesMatchingTest::class, class_uses_recursive($this))) {
            $this->addTestOptions();
        }

        $this->files = $files;
    }
```
I.e. it requires the Filesystem argument.

The reason why ide-helper trigger this is because the generate command introspects the Facades and it exposes that your Facade does not work due to the incorrect definition in your service provider.

Couple of roads leading to Rome:
- properly pass the required argument:
  ```php
          // Register the main class to use with the facade
          $this->app->singleton('cray', function (Container $container) {
              return new Cray($container->get('files'));
          });
  ```
- don't use the `'cray'` alias at all: in your Facade just reference the `Cray::class`
  ```php
      protected static function getFacadeAccessor()
      {
          return \JunaidQadirB\Cray\Console\Commands\Cray::class;
      }
  ```
  and remove the `->singleton()` part entirely.
  This leaves resolving the class to Laravel itself and it will correctly auto-inject the expected argument.

HTH!

**Comment by JunaidQadirB** [comment]
@mfn Thanks a lot for your time to explain in detail the issue at my end. 🙏
