### ISSUE TITLE
Ide Helper Not Working like it was before

### ISSUE THREAD

**Issue by Ham3D** [barryvdh/laravel-ide-helper#165]
i Have a working app in laravel 4 with ide helper 4.*  and another one in laravel 5 stable version.
ide helper works good enough in laravel 4 and php storm 8 , but in laravel 5 its not working good , i mean all commands are not there ,
for example there is no auto complete for : User::where
or any model::where
I dont know if it helps but in laravel 4 with php storm , when i ctrl+click on a method for example on where
in User::where , phpstorm takes me to _ide_helper with that function , but now in l5 when i click on for example with in User::with , phpstorm takes me to \vendor\laravel\framework ... not  _ide_helper.php

**Comment by barryvdh** [comment]
Probably because you are extending the real Model class, not the Eloquent facade.

**Comment by Ham3D** [comment]
Thats Right , Somehow i remember a thing that its better to user model @taylorotwell , not Eloquent.
am right or there is absolutely no difference?

**Comment by barryvdh** [comment]
`Eloquent` is just an alias to `Illuminate\Database\Eloquent\Model`, so it doesn't matter.
If you don't use the ide-helper, you should probably use the Model directly, because you get some autocompletion at least. If you do use the ide-helper, using the Facade can give you autocompletion for some magic methods also.

**Comment by Ham3D** [comment]
Thanks @barryvdh
