### ISSUE TITLE
Mutator not showing up

### ISSUE THREAD

**Issue by Anahkiasen** [barryvdh/laravel-ide-helper#170]
Take the following model:

``` php
class MyModel extends Model
{
  /**
   * @return string[]
   */
  public function getWordsAttribute()
  {
    return json_decode($this->attributes['words']);
  }
}
```

The IDE helper will currently generate `@property string $words` because the database column is a `text`.
Other mutators get their documentation added properly, but not the ones that have a column of the same name in the database it seems

**Comment by barryvdh** [comment]
Are you sure other mutators are correct? I think I should add a reflection method to the attribute mutator to get it. Don't do that now I think:
https://github.com/barryvdh/laravel-ide-helper/blob/master/src/Console/ModelsCommand.php#L286

**Comment by Anahkiasen** [comment]
They're more or less correct, most just display `mixed` as type instead of what the mutator actually returns, but they're there

**Comment by Kurre** [comment]
Just wanted to bump this issue, since I've been "struggling" with same problems.

I have mutator which return Money object like this:
(slightly simplified example)
```php
/**
 * Ticket price
 *
 * @param $value
 * @return Money
 */
public function getPriceAttribute($value)
{
    if ($value !== null) {
        return Money::EUR($value);
    }

    return Money::EUR(0);
}
```
But since ModelsCommand doesn't look the docblocks for a return value, it's using the column type (like it should be in normal situation):
```php
/**
 * @property int $price
 */
```

My quick'n'dirty solution is this:
(https://github.com/barryvdh/laravel-ide-helper/blob/master/src/Console/ModelsCommand.php#L386-L390)
```php
//Magic get<name>Attribute
$name = Str::snake(substr($method, 3, -9));
if (!empty($name)) {
    $reflection = new \ReflectionMethod($model, $method);
    $phpdoc = new DocBlock($reflection);
    $type = null;

    if ($phpdoc->hasTag('return')) {
        $returnTags = $phpdoc->getTagsByName('return');
        $type = $returnTags[0]->getContent();
    }
    
    $this->setProperty($name, $type, true, null);
}
```

Not very elegant, but I works :)
Now I get:
```php
/**
 * @property Money $price
 */
```

So, i'm hoping that you, @barryvdh could take a another look on this issue when you have time.
This isn't really a big problem, but I would help to get these properties sorted out :)

**Comment by pinepain** [comment]
@Kurre, I guess you mean something like this - https://github.com/barryvdh/laravel-ide-helper/pull/389.

**Comment by mfn** [comment]
@barryvdh ide-helper looks at the phpdoc for _getters_ for some time already and handles these cases correctly, can be closed :}
