### ISSUE TITLE
Adding Alias in boot stops autocomplete

### ISSUE THREAD

**Issue by jonnywilliamson** [barryvdh/laravel-ide-helper#208]
Hi Barry,

I was wondering if you shed some light onto why the following happens.

I've created a package for L5, and it has a serviceprovider and facade/alias (name is `TG`) that normally get added to `app/config.php`.

When I do this and run, `ide-helper:generate` everything works well and I get code completion in PHPStorm.

However I wanted to help the user by removing the need to add the Alias manually in the `config/app.php` file.

So, in my service provider boot method, I do this:

`LaragramServiceProvider.php`

``` php
    /**
     * Bootstrap the application services.
     *
     * @return void
     */
    public function boot()
    {
        $loader  = AliasLoader::getInstance();
        $aliases = Config::get('app.aliases');
        if (empty($aliases['TG'])) {
            $loader->alias('TG', 'Williamson\Laragram\Facades\LaragramFacade');
        }
    }

```

This works, in as much that the code works and I can type `php TG::someFunction($one, $two);``but now there is no code completion even after I run`ide-helper:generate`

All I get when I type TG:: and look for code completion is the word "class".

Am I doing something wrong or is there a better way to be doing this?

Thanks!

**Comment by mfn** [comment]
- upfront, I don't think is a "good idea ™️", Facades are and should stay optional
- the referenced package doesn't implement this, probably because it didn't work hence this issue
- the class reference is wrong (at least right now), it's supposed to be `\Williamson\Laragram\Laravel\LaragramFacade`
- I debugged it so far that the reason `\Barryvdh\LaravelIdeHelper\Alias` rejects is that `\Barryvdh\LaravelIdeHelper\Alias::detectRoot` marks it as `false` because this call fails https://github.com/barryvdh/laravel-ide-helper/blob/4aa919c09f4746ed53748e84484d1ad756d98c19/src/Alias.php#L277
  The alias/facade does not properly return the root facade
- when I _manually_ added the ServiceProvider and the alias, it _also_ did not work

```
~/tmp/laravel/laravel-7 $ ./artisan ide-helper:generate
Exception: get_class() expects parameter 1 to be object, null given
Skipping \Williamson\Laragram\Laravel\LaragramFacade.
Exception: get_class() expects parameter 1 to be object, null given
Skipping \Williamson\Laragram\Laravel\LaragramFacade.
A new helper file was written to _ide_helper.php
```
Makes me think if there's a bug with the package

The error
> `Exception: get_class() expects parameter 1 to be object, null given`

is because `getFacadeRoot` returns `null` for some reason.

@jonnywilliamson can you check?

**Comment by mfn** [comment]
No response on 5 year old issue => closing
