### ISSUE TITLE
Install instructions are incorrect

### ISSUE THREAD

**Issue by andrewjwolf** [barryvdh/laravel-ide-helper#227]
in readme.md
Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class,
should just be:
Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider

**Comment by barryvdh** [comment]
That's the class notation as used in Laravel 5.1. It's a php 5.5 feature

**Comment by barryvdh** [comment]
`Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class,` is the same as `'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider'`

**Comment by andrewjwolf** [comment]
if you can assume that more thant 50% are not running php 5.5. I would make a notation... I would predict that adoption would increase.

**Comment by barryvdh** [comment]
Well, Laravel 5.1 is the current Laravel releases (+ LTS version) which is currently targeted. New users should use 5.1, that's why the readme was updated. And Laravel 5.1 requires PHP 5.5

I would hope that people are using PHP 5.5. PHP 5.4 doesn't have active support anymore. http://php.net/supported-versions.php
