### ISSUE TITLE
PhpStorm 9.0 always finds declarations in _ide_helper.php

### ISSUE THREAD

**Issue by scottconnerly** [barryvdh/laravel-ide-helper#233]
When I Go To -> Declaration, it jumps to _ide_helper.php rather than the actual definition.

I didn't have this issue with PhpStorm 8.0, so I suspect it's related to that recent upgrade, but I can't be sure.

**Comment by rentalhost** [comment]
Do you mean something like: when you go to declaration of `Schema` facade, it jumps to `_ide_helper.php` instead of `Illuminate\Support\Facades\Schema`?

If is that, I guess that it works as expected. If you need go to `Illuminate\Support\Facades\Schema`, just go to declaration again on current file.

**Comment by shehi** [comment]
Agreed with @rentalhost , it is as expected and been this way for eternity, at least where Facades are concerned. For real methods such as ```app('events')``` it goes where it should. (Yet another reason why one shouldn't use Facades :P )
