### ISSUE TITLE
Autocompletion for Facades only shows direct Facade functions

### ISSUE THREAD

**Issue by bequadrat** [barryvdh/laravel-ide-helper#245]
I got the ide-helper:generate artisan command to work, which generates a _ide_helper.php in the project's root directory that seems to get parsed by PhpStorm. Autocompletion however only seems to resolve direct functions of the Facade class. Am I missing something?

<img width="561" alt="bildschirmfoto 2015-08-04 um 15 43 38" src="https://cloud.githubusercontent.com/assets/5172241/9061981/9c94cfb4-3abf-11e5-8926-724223c5450c.png">

**Comment by bebnev** [comment]
Which namespace are you using for `Log` class ?
`Illuminate\Support\Facades\Log` ?

**Comment by bequadrat** [comment]
Yep

**Comment by bebnev** [comment]
So that is the point.
Laravel is using aliases (`app.php => alias`) for it classes and ide-helper is generating autocomplete files according that aliases.
So try using simple namespace:
`use Log;`
Or in your code `\Log::` which is the same;

And when you set the namespace to the Facade class, IDE wil have nothing to do except showing the functions from that Facade class.

**Comment by bequadrat** [comment]
Ah!!! This does the trick! Thanks alot @bebnev!
