### ISSUE TITLE
Class App\Http\ not found

### ISSUE THREAD

**Issue by bluemanos** [barryvdh/laravel-ide-helper#254]
I wrote useful command to run 3 laravel-ide-helper at once: https://gist.github.com/bluemanos/479ae8259b28643a4b11

The command is of course registered in Kernel.php, but for some reason some of call() placed in that code is throwing an exception. The strangest thing is that if I run each laravel-ide-helper command manually than everything is working fine.

![screenshot_2015-08-17_21-27-24](https://cloud.githubusercontent.com/assets/9991002/9314046/c3f4b454-4526-11e5-88a3-e6ccb9e0c4b5.png)

The next strange thing is when I comment line with the second call() than the command is running properly.

What's wrong? How to avoid the Exception of Class 'App\Http\' not found ??

I'm using Laravel 5.1.10.

**Comment by bebnev** [comment]
Hello. The problem is connected with two things:
1) `ClassMapGenerator` class, function `findClasses` - in the last tagged version it face with some problems in dealing with `::class` constraints. So when ide-helper is trying to loadModels walking through `app` folder it finds `Kernel.php` file with something like this:
```php
protected $commands = [
        \App\Console\Commands\Inspire::class,
        \App\Console\Commands\DevCommand::class
    ];
```
And as a return ClassMapGenerator returns three classes:
```php
App\Console\Kernel.php;
App\Console\;
App\Console\;
```
As we see App\Console\ is not really a valid class.
2) When we use `ide-helper:models` separately from `ide-helper:meta` command it works well, because it is using default laravel autoloader, and `class_exists` just returns `false`. But when we use it after `ide-helper:meta` the command will use also another autoloader function defined in `ide-helper:meta` command in `registerClassAutoloadExceptions` functions which throw an exception when class does not exist.

So the easiest workaround will be to change the order of calling commands, like so:
```php
$this->call('ide-helper:generate');
$this->call('ide-helper:models', ['--nowrite' => 'No']);
$this->call('ide-helper:meta');
```

or you can unregister the last autoloader functions before calling `ide-helper:models`:
```php
$this->call('ide-helper:meta');
$functions = spl_autoload_functions();
spl_autoload_unregister(end($functions));
$this->call('ide-helper:models', ['--nowrite' => 'No']);
```

**Comment by mfn** [comment]
@bluemanos is this still an issue? I think nowadays this works correctly?

**Comment by bluemanos** [comment]
@mfn cant confirm this now.

Generally the issue is related with #216 and as you mentioned there, it is working fine in current version of ide-helper :) Lets close the issue.
