### ISSUE TITLE
Should ide-helper:models be generating phpDoc for the magic Eloquent\Model static methods?

### ISSUE THREAD

**Issue by jessedc** [barryvdh/laravel-ide-helper#259]
I have recently setup a new Lumen project (v5.1.3) and noticed the instance methods from `Eloquent\Builder` provided to `Eloquent\Model` by using `Model::__callStatic()` and `Model->__call()` internally are not added to the phpDocs generated by `ide-helper:models`.

One example directly from  [the Larvel 5.1 documentation](http://laravel.com/docs/5.1/eloquent#eloquent-model-conventions) is the `::find()` method.

<img width="398" alt="screen shot 2015-08-26 at 6 50 18 am" src="https://cloud.githubusercontent.com/assets/17407/9479459/e09915e6-4bc0-11e5-9b45-786a0aaa9289.png">

My observation is this call to ::find() is caught by `__callStatic()` and `__call()` methods of Eloquent\Model and proxied to `\Illuminate\Database\Eloquent\Builder`.

<img width="728" alt="screen shot 2015-08-25 at 9 51 58 pm" src="https://cloud.githubusercontent.com/assets/17407/9480110/74b2a636-4bc4-11e5-888e-c7efeb6be163.png">

These methods can be added to the phpDocs of the model with @method hints like the following: 

``` php
/**
* @method static \Illuminate\Database\Eloquent\Model|\App\Models\Cafe find($id)
*/
```

My question is, **should these magic methods from Builder be added to Model subclasses by `ide-helper:models`**?  Or should the Laravel documentation be updated instead?

Worth noting that this whole situation can also be avoided by using the builder directly via the `query()` method.

``` php
$cafe = Cafe::query()->find($cafeId);
```

> The [find() method was defined in 5.0](http://laravel.com/api/5.0/Illuminate/Database/Eloquent/Model.html#method_find) but are no longer defined on the `Eloquent\Model` as of 5.1.

**Comment by rentalhost** [comment]
I'll works if you extends from `Eloquent` facade. But I think that it need to works directly from `Eloquent\Model` too.

**Comment by bebnev** [comment]
I think that having such methods in Model docblocks is a real overhead, because find is only one "magic" method from EloquentBuilder. Then somebody will want methods from the QueryBuilder which are also called with __call/__callStatic.

So the easiest workaround, if you need autocompletion, is to extend `Eloquent` instead of` Eloquent\Model`, as @rentalhost said. Or, if you don't want to extend `Eloquent`, you can set something like this to the docblock of your model:
```php
/**
 * App\User
 *
 * @mixin Eloquent
 */
```

**Comment by icedfish** [comment]
Aha, such a tricky but useful workaround ~

**Comment by Francismori7** [comment]
@bebnev Very smart of the @mixin tag. Great work.

**Comment by shehi** [comment]
I believe ```@mixin``` is a neat solution. Shouldn't we close this issue?

**Comment by Francismori7** [comment]
@shehi it should generate the @mixin itself first IMO

**Comment by shehi** [comment]
@Francismori7 Agreed.

**Comment by brazenvoid** [comment]
I have 5.1 and a BaseModel in the inheritance chain which extends from Eloquent. Even with this the methods like find will always make the ide think that the class returned is Eloquent/Model rather than the calling model class.

We have over 1K models encompassing our sites to sales to warehousing to logistics. For our 50+ developers this plugin is a godsend but imagine adding the two static method definitions to the models when a scheduled reset is run through artisan(!) and then you can understand how a godsend turns into a god's wrath...

**Comment by mfn** [comment]
@barryvdh this is already fixed due to `@mixin` support long time ago, issue can be closed :}
