### ISSUE TITLE
Support for \Illuminate\Support\Fluent

### ISSUE THREAD

**Issue by blackakula** [barryvdh/laravel-ide-helper#262]
For all the methods, that return `\Illuminate\Support\Fluent` I would like to have IDE suggestions for fluent methods. For example `\Illuminate\Database\Schema\Blueprint::integer()` would suggest all the methods of `\Illuminate\Database\Schema\Blueprint::integer`. To achieve this it's easy to add next code in `_ide_helper.php`:

``` PHP
namespace Jenssegers\Mongodb\Schema {
    class Blueprint {
        public function integer($column, $autoIncrement = false, $unsigned = false) {
            return new static;
        }
    }
}
```

Result:
![fluent](https://cloud.githubusercontent.com/assets/156983/9962088/58d2426a-5e24-11e5-80dd-c8eaecb7a563.png)

The same for all methods of validators, etc.

**Comment by brazenvoid** [comment]
+1

**Comment by shehi** [comment]
+1

Can't you just create a PR and send it in? Just make sure it works well please.

**Comment by tylercrompton** [comment]
+1. However, the only problem is that it is impossible for a 100% working solution. The `Fluent` class lets you call any method, set any attribute, etc. even if doing so wouldn't do anything. Its class name is quite fitting; it is fluent in that it can be used for many purposes because it has dynamic capabilities. For example, when you call a method on a `Fluent` object, it just stores the method name and parameters. It doesn't actually do anything. The programmer (in this case, the Laravel developers) are responsible for using the stored values to actually do what the user of the class intended. That's why `Fluent` is in the `\Illuminate\Support` namespace.

I don't think that it would hurt to add the standardized "functions" and "attributes" of it. However, `Fluent` is used in different contexts, so all of the unrelated stuff would still show (which could arguably result in confusion). Laravel IDE Helper doesn't have the power to implement a full solution.

The ideal solution would be for JetBrains to take some of the PyCharm's dynamic magic sauce and pour it on PhpStorm.

**Comment by shehi** [comment]
@tylercrompton I am rather new to Python, but if the idea re PyCharm is viable, could you open a ticket with Jetbrains please?

**Comment by wstoettinger** [comment]
+1

**Comment by m3esma** [comment]
Please see my comment [here](https://github.com/barryvdh/laravel-ide-helper/issues/193#issuecomment-167346786)

**Comment by dmitry-ivanov** [comment]
+1

**Comment by Narcotic** [comment]
+1

**Comment by jbreuer95** [comment]
+1

**Comment by michaelpittino** [comment]
Any chance we can get this included in the ide-helper?

**Comment by Mythos** [comment]
Support for this would be awesome.

**Comment by Evertt** [comment]
Yes I'm using Fluent with some other classes too now and it would be awesome if ide-helper could find out which macros have been registered and then create autocompletion data for that.

**Comment by golubkovden** [comment]
Now, you can use `'include_fluent'  => true,` in your ide-helper config file.

**Comment by JohnnyWalkerDesign** [comment]
@m3esma solution works fantastically.

Just adding the following to the very bottom of _ide_helper.php

```
namespace Illuminate\Support{
    /**
     * @method Fluent first()
     * @method Fluent after($column)
     * @method Fluent change()
     * @method Fluent nullable()
     * @method Fluent unsigned()
     * @method Fluent unique()
     * @method Fluent index()
     * @method Fluent primary()
     * @method Fluent default($value)
     * @method Fluent onUpdate($value)
     * @method Fluent onDelete($value)
     * @method Fluent references($value)
     * @method Fluent on($value)
     */
    class Fluent {}
}
```

**Comment by SJ732** [comment]
@golubkovden thank you, this solved the problem

**Comment by decadence** [comment]
It does not help with this case:

```php
$table->foreign("parent_id")
            ->on("pages")
            ->references("id");
```
PhpStorm doesn't see `references` method.

**Comment by barryvdh** [comment]
Is now default on
