### ISSUE TITLE
Session store not set on request

### ISSUE THREAD

**Issue by maaxxicarvalho** [barryvdh/laravel-ide-helper#271]
Hi,

I'm receiving the bellow error messagem when trying to load : php artisan ide-helper:generate

```
[RuntimeException]
Session store not set on request.
```

**Comment by icemanblas** [comment]
I'm having the same issue when I try to login or to make an AJAX request. I think it's not 'ide-helper' related problem, but it is the Session configuration itself. However, I'm not able to solve it.

**Comment by maaxxicarvalho** [comment]
@icemanblas hi, thank for the feedback. Yes, maybe its not about ide-helper. I'll look for Session problems.

**Comment by MrCrankHank** [comment]
Did you find a solution?

**Comment by josh18** [comment]
Also having the same issue (just upgraded to Laravel 5.2) and can't seem to find a solution.

**Comment by icemanblas** [comment]
In my case, I simply created fresh project and imported all custom files manually. This is not of any help, but that's just what i did. That was a few months ago.

Recently, while browsing, I came across some article which said the problem is related to the `routes.php` file and the way middleware is used within some routes (Laravel 5.1). Sorry, can not provide link or details, just a guidance where the problem lays.

While this is not a good answer or solution, it might be of some help.

**Comment by josh18** [comment]
I narrowed it down to having `Request::session()` in `app/Providers/AppServiceProvider`. Still not sure how to fix it though. It should be using the normal global middleware defined in`app/Http/Kernal.php -> $middleware` right?

**Comment by barryvdh** [comment]
I don't think this is related to the ide-helper at all

**Comment by MrCrankHank** [comment]
Yep, i think your right. I remember getting the error on other artisan commands as well. Still not sure what's causing this though.

**Comment by akhzarjaved** [comment]
Any solution on this issue ?

**Comment by mfn** [comment]
I also don't think it's related to ide-helper.

Can someone put a public repo which reproduces the problem?
