### ISSUE TITLE
Still getting Method not found in class.

### ISSUE THREAD

**Issue by raysn0w** [barryvdh/laravel-ide-helper#291]
What the problem is:

For example: inside my resource controller, Customer::find($id); It get the method "find" not found warning, If I go to the Costumer Class and extend it to Eloquent that problem goes away, but the methods that I personally created for the class get me the method not found warning in the IDE.

I don't have a problem with "new Customer()" the problem is when I Involve Customer::find($id).

I have also run: "php artisan clear-compiled", "php artisan ide-helper:generate", "php artisan optimize" and php artisan ide-helper:models.

Any help please?

Thanks!

**Comment by raysn0w** [comment]
Just in case:
PHPStorm 10.2
Laravel 5.1.26

**Comment by mishtershmart** [comment]
I'm having the same issue in Intellij IDEA. 

I think this might be related to this issue here – https://youtrack.jetbrains.com/issue/WI-28394. If it is, it's a massive pain, as it's killing productivity on a number of my projects. 

I'd suggest heading to the issue above and voting on it.

**Comment by brazenvoid** [comment]
The dev is not interested to implement support for those methods unless you submit a PR yourself.

**Comment by hansott** [comment]
@raysn0w The reason why PHPStorm thinks the method ::find does not exist is because they are redirected to a query builder instance:

```php
    /**
     * Handle dynamic method calls into the model.
     *
     * @param  string  $method
     * @param  array  $parameters
     * @return mixed
     */
    public function __call($method, $parameters)
    {
        if (in_array($method, ['increment', 'decrement'])) {
            return call_user_func_array([$this, $method], $parameters);
        }

        $query = $this->newQuery();

        return call_user_func_array([$query, $method], $parameters);
    }

    /**
     * Handle dynamic static method calls into the method.
     *
     * @param  string  $method
     * @param  array  $parameters
     * @return mixed
     */
    public static function __callStatic($method, $parameters)
    {
        $instance = new static;

        return call_user_func_array([$instance, $method], $parameters);
    }
```

Thus, PHPStorm can't know the method exists... Does that answer your question? If so, close this issue :wink:

**Comment by jtwiegand** [comment]
I'm getting a similar issue.  I don't think this is about namespaces as suggested earlier.

I think this is because PHPStorm can't understand that findOrFail, and similar functions, returns an instance of a particular extension of a model, not an instance of Model or Eloquent.

Extending Eloquent instead of Model makes findOrFail complete fine, but the return of that function isn't know to the IDE to be an instance of whatever Model it found.

For example:
`$some_model = Some_Model::findOrFail($id);` // this works fine
`$some_model->some_relationship();`  // methods on model won't autocomplete

The IDE thinks it's an instance of either a collection or a Model, not an instance of Some_Model, so the IDE won't know about its methods or properties unless I type hint it by passing the object to an intermediate function.

**Comment by donnygunawan93** [comment]
@jtwiegand I got also, u know how to fix?

**Comment by mfn** [comment]
@barryvdh this are basic things all got fixed and working in the current era, vote for closing :}
