### ISSUE TITLE
Autocomplete for \Illuminate\Support\Facades\Input not shown in laravel 5.2

### ISSUE THREAD

**Issue by emharis** [barryvdh/laravel-ide-helper#309]
I use Netbeans 8.1 and Autocomplete for \Illuminate\Support\Facades\Input not shown in laravel 5.2

**Comment by naerymdan** [comment]
Probably because Input is not registered as a facade in your config/app.php file?


```
    'aliases' => [
        ...
        'Input'     => Illuminate\Support\Facades\Input::class,
        ...
    ],
```

if you add it and then regenerate the `php artisan ide-helper/generate` It'll add the missing Input facade stuff to your helper file.

That said, I think Laravel 5.2 is going with the idea of using the Request injected in your controller function instead of using the Input facade nowadays: https://laravel.com/docs/5.1/controllers#dependency-injection-and-controllers

**Comment by ddctd143** [comment]
It won't work if you will include it like this in your class file:
use \Illuminate\Support\Facades\Input;

Try to include it in top of class like this:
use \Input;
and then check if autocomplete functionality is working

**Comment by morfin** [comment]
Including Facade as \Input did the job.

**Comment by emharis** [comment]
Thank for all.....
