### ISSUE TITLE
Using the IDE helper in a composer package

### ISSUE THREAD

**Issue by offroff** [barryvdh/laravel-ide-helper#319]
I'd like to use the IDE helper when working with composer packages. Did anyone do that?

I guess I need to install artisan, is that the right way?

**Comment by barryvdh** [comment]
What do you want exactly? WHy?

**Comment by offroff** [comment]
I'm developing a laravel 5 application and think your package helps a lot. Then I started to extract some of the code into packages and figured I should work with the packages in isolation but then I realized I don't have access to the ide helper anymore.. I found it pretty difficult to work with packages for other reasons as well and now I'm working directly in the /vendor folder instead and that helps me with this issue (and some other issues). Still I feel like I'm doing something wrong but at least I don't have this specific problem anymore. So this issue can be closed but if you or someone else has some hints please share :)

**Comment by mfn** [comment]
@offroff I believe you can. I just recently added tests to _this_ repository, which demonstrates that this package can be run without the full frame as a package (by using https://github.com/orchestral/testbench ), so I don't see why this wouldn't work in _your_ package, when you:
- use https://github.com/orchestral/testbench
- make ide-helper a dev dependency
- and use it there

And may need to some more setup / bootstrapping, but should be doable.

Mildly related, some time I ago I opened https://github.com/barryvdh/laravel-ide-helper/issues/756 because I use this package also without a full-framework and had to jump through some hoops, which I outlined. Maybe those things apply, maybe they don't.

**Comment by glaucomorais** [comment]
For me, I just added the service provider for Laravel IDE Helper in the `testbench.yml` file, then I ran `testbench package:discover` and the `ide-helper` commands appeared.
