### ISSUE TITLE
Route::auth is missed

### ISSUE THREAD

**Issue by ebuster** [barryvdh/laravel-ide-helper#355]
I am added pre generated version from https://gist.github.com/barryvdh/5227822 and see that Route::auth() is still underlined as warning in PHPStorm.

**Comment by Resin01** [comment]
+1

**Comment by amerov** [comment]
+1

**Comment by mfn** [comment]
@barryvdh I don't think there's much to do anymore because this feature, to the best how I understand it, was removed in Laravel and extracting into different package altogether; as in there's no `Route::auth()` anymore => https://github.com/laravel/framework/commit/aebd93d5f67de55473f3f0ff5056abbfc5972102

This was done in fact for L7, so `Route::` before/after L7 changes in this regard. I'm not using https://github.com/laravel/ui but the docs at https://laravel.com/docs/7.x/frontend suggest to me it works differently and `Route::auth()` is simply history.

I _think_ it would be fixable by gong to the L5/L6 route facade and adding `@methods` there. But I doubt the will accept this for L6 when it's already gone from L7.

@barryvdh I vote for closing this :}
