### ISSUE TITLE
Request: Pass wildcard characters when generating model docs

### ISSUE THREAD

**Issue by abishekrsrikaanth** [barryvdh/laravel-ide-helper#41]
Hi Barry,

This is a request for a good to have feature, not sure how easy or difficult this is to implement. Is it possible to have wildcard characters when generating model docs

For example:

```
php artisan ide-helper:models User*
```

which will look for all the Models that starts with `User` and generate the docs for all of them

or

```
php artisan ide-helper:models %User
```

which will look for all the Models ending with `User` and generate the docs for all of them

or

```
php artisan ide-helper:models %User%
```

which will look for all the Models containing the characters `User` and generate the docs for all of them

**Comment by bytestream** [comment]
@barryvdh not sure that this is quite the same request, but I could do with the ability to either exclude directories similar to https://github.com/barryvdh/laravel-ide-helper/pull/135 or the ability to wildcard directories

Something simple like this might work?
````
$models = array();
foreach ($this->dirs as $dir) {
    foreach(glob((base_path() . '/' . $dir), GLOB_ONLYDIR) as $dir) {
        foreach (ClassMapGenerator::createMap($dir) as $model => $path) {
            $models[] = $model;
        }
    }
}
````

I say simple, because that allows you to only wildcard single subdirectories. You couldn't use `**` any number of subdirectories.  But there is this: https://gist.github.com/funkjedi/3feee27d873ae2297b8e2370a7082aad

Thoughts?

**Comment by mfn** [comment]
@abishekrsrikaanth is this still relevant? What's the use-case for generating the phpdoc for only certain **models**?

I checked the issues (open/closed) and this is the only one suggesting such a feature. It sounds edge-case/y and might not be worth the adding/maintaining.

@bytestream there's a config `model_locations` and it recently has received support for glob patterns to recursively descent into _directories_ => https://github.com/barryvdh/laravel-ide-helper/pull/921
So I think your use-case is covered.

**Comment by mfn** [comment]
Furthermore I just realized the config already has `ignored_models` so I think it's already possible to achieve everything here anyway.
