### ISSUE TITLE
Exception: Missing argument 1 for (model)  when running :models

### ISSUE THREAD

**Issue by tarreislam** [barryvdh/laravel-ide-helper#411]
So all my models uses a Trait which contain many functions. 

This particular function causes **ide-helper:models** to throw an exception

```
    /**
     * @param $model
     * @return mixed
     */
    public function belongsToOne($model)
    {
        $model_first = $this->belongsToMany($model)->first();

        return $model_first ?: null;
    }
```

```
Exception: Missing argument 1 for App\Models\fhh_property::belongsToOne(), called in \barryvdh\laravel-ide-helper\src\Console\ModelsCommand.php on line 373 and defined
Could not analyze class App\Models\fhh_property.

```

So I have to remove that function each time I want to run the command.

**Comment by mfn** [comment]
My detective work lead me to believe he following happened:
- In `\Barryvdh\LaravelIdeHelper\Console\ModelsCommand::getPropertiesFromMethods` there is a check for `belongsTo` and it uses `stripos($code, $search)`, thus I think it also matched `belongsToOne` due to this
- However https://github.com/barryvdh/laravel-ide-helper/pull/664 add protected for relations which require arguments and skips them

@barryvdh I think this issue is fixed and can be closed :}
