### ISSUE TITLE
PhpStorm 2017.1 EAP Go to implementation on Facades goes to the _ide_helper.php file

### ISSUE THREAD

**Issue by alexgmin** [barryvdh/laravel-ide-helper#464]
> Version 2.3.2

On PhpStorm 2017.1 EAP, "Go to implementation" and "Go to declaration" on, for example, Log::debug, goes to the _ide_helper.php file.

![image](https://cloud.githubusercontent.com/assets/8340441/23893838/4aa53dc8-08a0-11e7-9ac8-d480ad0835ae.png)

Also, and I don't know if this is related, "Go to implementation" on 
` return \Monolog\Logger::debug($message, $context);`
Does nothing, while "Go to declaration" works as expected.

**Comment by bbashy** [comment]
Similar story

![](https://d.pr/i/bs0I/3AYtS3Un.jpg)

**Comment by Alexgmin** [comment]
This still happens on the last EAP
PhpStorm 2017.1 EAP
Build #PS-171.3780.55, built on March 15, 2017

**Comment by barryvdh** [comment]
Thats because we define the methods in the ide_helper. They're not actually in the Facade, but called dynamiccally. So not sure what would be better.

**Comment by DarkGhostHunter** [comment]
Can this be overriden by the [Haehnchen/idea-php-laravel-plugin](https://github.com/Haehnchen/idea-php-laravel-plugin)?

**Comment by DMeganoski** [comment]
Yea, this isn't really this package's issue... without this package, the 'goto' simply wouldn't work for facades. This kind of tricks the IDE into recognizing facades by creating that file with the appropriate class names and functions, unfortunately this mean when you use the 'goto' it's going to where it sees it declared... which is ide_helper.php.

You can, however simply 'goto' the function that is returned and get to where you were trying to go, it just means an extra step and one more open tab, which for me is annoying enough to bring me here looking for a solution.

I doubt there is any solution that this package could achieve, however considering said IDE plugin refers to this plugin, it could probably be taught to jump straight to the returned function instead of opening ide_helper.php.

I'm going to open an issue on that package and see what his thoughts are.

**Comment by mfn** [comment]
@barryvdh this is expected and they way it works, I think this issue can be closed :}
