### ISSUE TITLE
Update to Laravel 5.4 cannot read phpdocs of Model or Eloquent object

### ISSUE THREAD

**Issue by atlas-wong** [barryvdh/laravel-ide-helper#535]
When my project is 5.3, ide-helper works like a charm:
![default](https://user-images.githubusercontent.com/29590700/27735155-bd1e155c-5dd0-11e7-8b5f-2cf621882d08.png)

But when I updated to 5.4, nothing show with the same flow:
![default](https://user-images.githubusercontent.com/29590700/27735211-fcbf0a4a-5dd0-11e7-8e2e-ef008399ae7d.png)

The version of PhpStorm is 2017.1.4

Could anyone point out the reason and the solution for this issues?

**Update:**
I found that if I do not use first(), the comment can pop out again, but of course it is not work
This should be Laravel 5.4 comment issue, right?

**Self fix method:**
1. Go to ./vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php
2. Go to first function return part, in my case is line 71 (also applicable for other function that should return a model object)
3. Change the word "mixed" to static (in Laravel 5.3, it is \Illuminate\Database\Eloquent\Model|static|null)
4. Run "php artisan ide-helper:generate"
5. Revert the word static to mixed (or keep as 5.3 \Illuminate\Database\Eloquent\Model|static|null)
6. Enjoy the auto complete again!

**Comment by mauriciomateus** [comment]
Hi. I used to run ide-helper models command and it asked me if I would like to have the annotations written directly to the models or to a file that was kind of named like _ide-helper-models.php. I used to take that option and eloquent scope methods (all models inheriting from a class that extends eloquent), were available in phpstorms code hints as statif methods.

With one recent update the console does not prompt me to do anything. It just creates a file named models.php, but Eloquent scopes are not understood by pho storm, the do not show in the ide hints.
It would be nice if it could be rolled back to the way it worked before. Seeing the available Eloquent scopes with out looking into de models was super useful.
The generated models.php file does not take the Eloquent scope methods inherited or even written in the very models.

Thanks in advance.

**Comment by Artistan** [comment]
related?
https://github.com/barryvdh/laravel-ide-helper/issues/541#issuecomment-317411918

**Comment by atlas-wong** [comment]
@Artistan Yes, it should be related, and the pull request should ask the laravel team to revert the comment of the return type instead of ask them to add the mixin comment which is not related to laravel in their mind.

**Comment by Artistan** [comment]
@atlas-wong - the `@mixin \Eloquent` addition is an issue with PhpStorm, not with Laravel.
PhpStorm does not support magic calls to non-static methods via __callStatic.  Please read the comments and add feedback at the PhpStorm website. Reverting the `@mixin` additions does not help, they actually help a great deal with proper usage. I also have a fix request into ide-helper which auto adds the \Eloquent tag to all model instances, it should just add it to the Eloquent\Model as I suggested (until PhpStorm can support static methods).  We should add the static method calls to the doc blocks also, since that would be the best solution without assistance from other parties.

**Comment by Artistan** [comment]
Here is an example of why proper type hinting on the Model class is helpful
http://blog.geekslikeshinythings.com/2017/07/laravel-and-phpstorm-needed-proper.html

**Comment by barryvdh** [comment]
So with this update, what do I need to change to make it better?

**Comment by Artistan** [comment]
I am looking into your code @barryvdh, I was hoping to submit a fix for you before you asked ...
Basically, you do NOT need to have the \Eloquent reference on individual model instances.
It is just needed on the `vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php`

![image](https://user-images.githubusercontent.com/801349/28570598-735d5260-7104-11e7-91b4-269c6f6d4b3e.png)

**Comment by barryvdh** [comment]
Yeah I had the `\Eloquent` mixin because that references the _ide_helper.php file, which has the methods from both builders. But obviously doesn't work without the facades file.

But if you models extend the Model class, which in his turn includes the mixins, why do we need to change the models at all? Shouldn't they be inherited?

**Comment by Artistan** [comment]
Yes, they should. But there is no @mixin for static methods. The \Eloquent mixin that is provided by the _ide_helper.php provides references to the static calls to non-static methods via __callStatic on the (new static)->$method...

**Comment by Artistan** [comment]
there is no "static" mixing for PhpStorm
https://github.com/barryvdh/laravel-ide-helper/issues/541#issuecomment-317411918

**Comment by atlas-wong** [comment]
The phpdoc in the latest code of laravel framework is reverted, so there should be no update is required in ide-helper.

**Comment by Artistan** [comment]
Not sure where you are looking @atlas-wong 

**Upcoming ...**
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Model.php

**Current - v5.4.30**
https://github.com/laravel/framework/blob/b9a64955f4278f45ac348a6e000b5ecc85da167a/src/Illuminate/Database/Eloquent/Model.php

**Comment by Artistan** [comment]
apparently that is an unrelated issue :)

**Comment by mfn** [comment]
@barryvdh This references outdated versions and nowadays everything works as expected, this also looks another thing which was fixed with `@mixin`, it also links to this popular comment https://github.com/barryvdh/laravel-ide-helper/issues/541#issuecomment-317411918 . I don't see anything new here and thus vote for closing this issue :}
