### ISSUE TITLE
Using Laravel IDE Helper with version 5.5

### ISSUE THREAD

**Issue by ivansammartino** [barryvdh/laravel-ide-helper#585]
Hello, and sorry for the dumb questions
I'm using a fresh installation of Laravel 5.5 and I have some doubts about installing IDE Helper:

1. Even with the brand new package discovery feature do I have to manually add the service provider `Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class,` ? (please notice that I installed IDE Helper with `--dev` option)
2. in Laravel 5.5 there is no `"post-update-cmd"` command in `composer.json` file: so, how do I configure it to add the following lines?

```
"scripts":{
    "post-update-cmd": [
        "Illuminate\\Foundation\\ComposerScripts::postUpdate",
        "php artisan ide-helper:generate",
        "php artisan ide-helper:meta",
        "php artisan optimize"
    ]
},
```
Thanks a lot for your answers

**Comment by emilinet** [comment]
Just add it to your composer file as another json attribute.
(Require is one of the attribute)
ex 

```
{
 "require" : { 
  [PACKAGES]
 },
 "scripts":{
   "post-update-cmd": [
    "Illuminate\\Foundation\\ComposerScripts::postUpdate",
    "php artisan ide-helper:generate",
    "php artisan ide-helper:meta",
    "php artisan optimize"
   ]
 }
}
```

**Comment by rothso** [comment]
1. You should be good to go as long as you're using v.2.4.0, [when Auto-Discovery support was added](https://github.com/barryvdh/laravel-ide-helper/commit/0e4b9b77c3e6997b2e0ce16c01535c9da4760244), or newer. You don't need to manually add the service provider. Dev dependencies [will also be auto-discovered](https://medium.com/@taylorotwell/package-auto-discovery-in-laravel-5-5-ea9e3ab20518) whenever they are installed.
2. You can still use `"post-update-cmd"`, since [it's a Composer hook](https://getcomposer.org/doc/articles/scripts.md). The new configuration is:
    ```json
    "scripts": {
        "post-update-cmd": [
            "php artisan ide-helper:generate",
            "php artisan ide-helper:meta"
        ]
    },
    ```

Hope this helps 🙂

**Comment by mfn** [comment]
@barryvdh all question where answered, IMHO this is good to be closed :}
