### ISSUE TITLE
Line ending keeps changing to CRLF

### ISSUE THREAD

**Issue by anik786** [barryvdh/laravel-ide-helper#644]
Every-time I perform a command using this tool like:

    ./artisan ide-helper:models -W

It keeps changing all my models line endings from "\n" to "\r\n".

Is there any way to change this.

**Comment by mfn** [comment]
The ide-helper does not use `\r\n` (also doesn't use PHP_EOL which would be platform dependent), i.e. everything is hardcoded to `\n`; either with explicit `\n` or implicit due to the formatting of the source file.

Do you have vendor/ put in version control (git) which does some magic due to `autocrlf`?

Is this still an issue for you?

**Comment by anik786** [comment]
Hi. I have not recently have this issue. Perhaps it was fixed or another unrelated issue. So I'll close this issue. Thanks.
