### ISSUE TITLE
Some methods in facades are not showing up (e.g. Route::prefix)

### ISSUE THREAD

**Issue by anik786** [barryvdh/laravel-ide-helper#679]
The following does not seem to autocomplete correctly in PHPStorm.

     Route::prefix(...)

There are other examples, but I think this may be a common issue with some magic method in facades.

**Comment by digitv** [comment]
+1, for example `Auth::routes()` also missing

**Comment by Neokyuubi** [comment]
Yes please can anyone help us with theses two ?

**Comment by mfn** [comment]
`Route::prefix` works, I just tested (maybe because of https://github.com/laravel/framework/pull/24086 , not sure)

As for `Auth::routes()`, there' already an issue for this => https://github.com/barryvdh/laravel-ide-helper/issues/513

@barryvdh original issue works, other mentions is a dupe => IMHO issue can be closed! :}
