### ISSUE TITLE
[Request] Parse @method in class doc block

### ISSUE THREAD

**Issue by jarollz** [barryvdh/laravel-ide-helper#73]
In using Laravel Framework, I've built a class that provides magic functionality through implementation of __call. The class will be accessible through a Facade that is registered by my custom service provider.

The provided magic is documented in @method, i.e.

``` php
/**
 * Class MyClass
 * Built to do some work 
 *
 * @method mixed magic() the magical method
 * @method array magic2(\SomeClass $cls) another magic method
 */
class MyClass {
...
```

The class works as intended, however auto-complete isn't satisfactory as it seems that ide-helper hasn't been added to support this. Using the class directly and accessing the documented magic is OK, as the IDE that I use can identify @method doc block.

Please add support for this, 

For more detailed info on @method, please check http://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.method.pkg.html

**Comment by mfn** [comment]
This works for me, however what's missing from OP are some details.

```php
/**
 * @method mixed magic() the magical method
 */
class MyClass {
```

How do you call this Facade?

Because the common use-case for facades are "virtual static" calls (or whatever the term is 😄 ), so in your case this should be:
```php
/**
 * @method static mixed magic() the magical method
 */
class MyClass {
```
Then you can call it with:
```php
MyClass::magic();
```
and you get correct auto-complete IDE. Works for in PhpStorm at least.

ide-helper does it correctly (at least now?) because the class phpdoc is simply copied to the `_ide_helper.php` file.

@barryvdh I think there's nothing actionable and this can be closed :}
