### ISSUE TITLE
double declaration of models

### ISSUE THREAD

**Issue by alextime** [barryvdh/laravel-ide-helper#759]
Generating a helper model file on PhpStorm 2018.3 generates a multiple definition of all models and a warning every time a model it is called.

Am I doing something wrong? I do not know if it is related but Laravel Plugin is also not able to autocomplete views and some blade directives.

Thanks in advance

**Comment by joelharkes** [comment]
Similar issue where generation of methods like: `withTrashed` actually hides the instance methods from php intellisense (although, go to declaration navigation still works (ctrl + click)). Though this is probably a php storm issue.

**Comment by Cyb0rk** [comment]
Same here. Did I misconfigure PhpStorm? I marked the vendor/ folder as "excluded" in my project.

![image](https://user-images.githubusercontent.com/95137/55225894-fcc2ec80-5213-11e9-9ff2-4bcbcfeaca7d.png)

**Comment by MCMainiac** [comment]
Can confirm for PhpStorm 2019.1 and laravel-ide-helper 2.6.2

**Comment by lucacri** [comment]
Same here

**Comment by mokhosh** [comment]
same phpstorm 2019.2

**Comment by mfn** [comment]
For models, the workaround is to write them directly to the models with `--write` (also might want to consider `--reset`).

Otherwise there's not much which can be done: using the phpdoc in an external file by definitions means there's another value shallow duplicated the model names to add additional information.

@barryvdh there's no fix for this but a different way, I suggest to close this issue :}
