### ISSUE TITLE
Route::name() Laravel 5.5~5.7

### ISSUE THREAD

**Issue by garbinmarcelo** [barryvdh/laravel-ide-helper#762]
Hi,

When using the "Route::name()" facade in Laravel 5.5, in PHPStorm it gets as "Required parameter $routes missing", whereas with the version of Laravel 5.7 this does not happen.

What I noticed is that in the _ide_helpder.php file, in version 5.5 "Route name (string $value)" is already used in 5.7 "RouteRegistrar name (string $value)".

Would you have any way to adjust that?

Laravel 5.5
![image](https://user-images.githubusercontent.com/9335588/52167423-ed3a9200-2701-11e9-83f8-10948d10fa05.png)
_ide_helper.php
![image](https://user-images.githubusercontent.com/9335588/52167438-14915f00-2702-11e9-8eb6-6948dd848ba3.png)

---

Laravel 5.7
![image](https://user-images.githubusercontent.com/9335588/52167427-fcb9db00-2701-11e9-83d7-886a654d91c6.png)
_ide_helper.php
![image](https://user-images.githubusercontent.com/9335588/52167431-08a59d00-2702-11e9-84f3-9303e2ba7ed8.png)

**Comment by marcelogarbin** [comment]
any news for 5.5? anyone else with this problem?

**Comment by dbrown546** [comment]
Also having this issue with Laravel 5.5 in PHPSTORM. My entire routes file is highlighted yellow.

I think it's something to do with the groups, like domain, middleware, prefix. Single routes (outside groups) seem unaffected.

**Comment by maurosbu** [comment]
I'm on Laravel 5.5 and I have the same issue.

`Required parameter '$routes' missing.`

**Comment by blueshoonroy** [comment]
I too see my routes file as all yellow, but it works just fine.

**Comment by PouriaDiesel** [comment]
I used this:
```
use Illuminate\Support\Facades\Route;

Route::prefix('/')->group(function (){
    Route::get('/', function () {
        return view('welcome');
    });

    Route::get('/about',function (){
        return view('about');
    });
},'');
```

**Comment by mfn** [comment]
I can't quickly figure out on what end this was fixed; it works for me in L7 without errors:
![image](https://user-images.githubusercontent.com/87493/85914952-8d3b1300-b843-11ea-9b50-334bf0407725.png)

(it would be shown underlined if it wouldn't be recognized).

I could assume this was rather fixed _in laravel_ with some phpdoc change.

@barryvdh if my theory is correct that this was fixed in Laravel, no one is going back to L5.5 to fix this. OTOH it works in the current version of Laravel, I vote for closing this :}
