### ISSUE TITLE
Suggestions to automate ide-helper commands

### ISSUE THREAD

**Issue by MatanYadaev** [barryvdh/laravel-ide-helper#794]
Hi, how do you suggest to make ide-helper commands run automatically?
Should I `.gitignore` ide-helper files? Or should I not ignore them and run the commands using the CI tool.
We're a small dev team and I want to have always up-to-date models ide-helper.

**Comment by mortenscheel** [comment]
I've submitted a [pull request](https://github.com/barryvdh/laravel-ide-helper/pull/797) that makes it possible to update Model docblocks automatically when they are affected by a migration.

**Comment by dccampbell** [comment]
@MatanYadaev I recommend adding `/.phpstorm.meta.php` and `/_ide_helper*` to your `.gitignore`, and then using [Composer scripts](https://getcomposer.org/doc/articles/scripts.md) to keep it up-to-date. For example:
```
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover",
            "@ide-helper"
        ],
        "ide-helper": [
            "@php artisan ide-helper:generate",
            "@php artisan ide-helper:meta",
            "@php artisan ide-helper:models -N"
        ]
    }
```
Now anyone can use `composer run ide-helper` to update their local helper files, and having`"@ide-helper"` in the post-autoload-dump array ensures that it runs itself every time a composer install/update is done.

**Comment by giovannipds** [comment]
It'd be good to hear something of the main contributors on this issue. cc @barryvdh @mfn @JeppeKnockaert

**Comment by giovannipds** [comment]
One thing I'd like to add here is that I, personally, wouldn't set `@ide-helper` running at `post-autoload-dump`, since this is a script that also runs in production too and we wouldn't need/want ide-helper there (since this a dev dependency). I'd prefer sticking it to `post-update-cmd` as suggested at docs, since requires devs to do that. Also, got a problem recently running a deploy at AWS that ide-helper needed database connection to run and `.env` file was created just after composer installation, therefore, not `.env` when `post-autoload-dump` had run.

**Comment by dccampbell** [comment]
@giovannipds Glad you reminded me of this as I agree with you and moved away from using `post-autoload-dump` quite a while back. I usually opt just to run it manually now, but I think `post-update-cmd` is probably the best option for automating it since in theory `composer update` should only be happening in local environments. I'll update the post accordingly.

**Comment by giovannipds** [comment]
@dccampbell 👊🥂 o/!

**Comment by giovannipds** [comment]
@MatanYadaev what have we discussed here doesn't solve the issue for you? It'd be good to hear a feedback.

**Comment by MatanYadaev** [comment]
@giovannipds I'm already using the composer post install script for the meta and generate commands, it works excellent.
I suggest listening to MigrationsEnded event to dispatch the models command as well, it won't track new relations/scopes/accesors changes but it will help for sure.with new columns, and it will be very helpful.

**Comment by giovannipds** [comment]
@MatanYadaev nice tips! Read what I told @dccampbell above, `composer install` may run at production environments too... if you accomplished what you wanted it with this issue, consider closing it.

**Comment by dccampbell** [comment]
One last thought towards a potential new issue or PR:
One change of potential value would be for the package to offer a single command out-of-the-box to wrap those three up -- and to fail the `ide-helper:models` step gracefully with a warning if a DB connection can't be established (instead of failing with error).  

Then "automating" the process would be as simple as adding a single line to composer.json:
`"post-update-cmd": "@php artisan ide-helper:all"`

**Comment by giovannipds** [comment]
@dccampbell agreed.

**Comment by pindab0ter** [comment]
> @MatanYadaev I recommend adding `/.phpstorm.meta.php` and `/_ide_helper*` to your `.gitignore`, and then using [Composer scripts](https://getcomposer.org/doc/articles/scripts.md) to keep it up-to-date.

What is the rationale behind recommending adding it to `.gitignore`? What value does that add? IDE Helper can get out of date by adding accessors/mutators without backing fields that don't require a migration.

Personally I use a file watcher in PHPStorm to run the command every time a change is made to any Models file. I'm just curious as to why you wouldn't want to add the helper files to your VCS.

**Comment by giovannipds** [comment]
@pindab0ter I believe it's because two things:

1. It's a dev data, not needed for production;
2. Can be be auto-generated locally.

IMO.
