### ISSUE TITLE
Support Ardent relations

### ISSUE THREAD

**Issue by Cysioland** [barryvdh/laravel-ide-helper#90]
As in title. Eg.

```
public static $relationsData = [
  'author'  =>  [self::HAS_ONE, 'User', 'foreignKey'  =>  'author']
];
```

**Comment by elegantdevelopment** [comment]
+!

**Comment by Alexwijn** [comment]
+1

**Comment by mfn** [comment]
I'm being blunt here and would argue this does not belong in this library.

- As https://github.com/laravel-ardent/ardent#cleaner-definition-of-relationships-since-20 states, this just a different way of expressing _what is already possible_ in Laravel this but it's custom made (it resembles Yii and what I know from CakePHP) but in the end: it's non-Laraval-standard.
  If people thing they need this feature then they made the decision to go "non-standard" and thus have to live with that ide-helper does know about this.
  If someone wants to make a "ide-helper" plugin supporting this, IMHO this would be fine. I think this library can accomodate adjustments necessary to easy supporting this (but maybe it's already possible by overriding `\Barryvdh\LaravelIdeHelper\Console\ModelsCommand::getPropertiesFromMethods` and adding the relations after the fact somehow)
- Additionally, this library feels unmaintained: last commit 3 years ago, published packages only support L5.1 which we don't, PR for L6 already lies for month without feedback and we've already on L7

@barryvdh I vote for closing this :}

**Comment by mfn** [comment]
This also highlights an important fact regarding "maintenance": if ide-helper would have added support for this years ago, effectively it would be dead code already as ide-helper stopped supporting L5.1 so accepting features for external packages must truly be carefully weighted.
