### ISSUE TITLE
not working with Trait

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [barryvdh/laravel-ide-helper#98]
```
Loading model 'Cars\ItemsTrait'
Class Cars\ItemsTrait does not exist
```

trait code

```
<?php

namespace Cars;

trait ItemsTrait {
...
```

using in models

```
<?php 

namespace Cars;

class Disc extends \MyEloquent {

    use ItemsTrait;
...
```

**Comment by michabbb** [comment]
may i ask: i.e. "notifyNow" is unknown:

`$order->user->notifyNow(new ReservationCanceled($order));`  
  
but the parser should be able to see `use Notifiable;`  inside the model and "could" add:  

```
* @method notifyNow(Notification $notification, array $channels)
 * @method notify(Notification $notification)
 * @method routeNotificationFor($driver, Notification $notification)
```

because phpstorm still seems to have a problem with traits inside traits when it comes to code-completion,
this would be a nice help....

**Comment by mfn** [comment]
> because phpstorm still seems to have a problem with traits inside traits when it comes to code-completion,

Never heard of this. Do you have a bug reference?

> `$order->user`

Can you please share relevant parts from the Order model? phpdoc and relation definition.

IMHO this should work. Having the `Notifiable` on a model certainly correctly autocompletes `->notifyNow()`, and all the others you mentioned, for me:
![image](https://user-images.githubusercontent.com/87493/95767859-b201ac00-0cb5-11eb-8bcf-f62054d2309e.png)

This using the latest PhpStorm (EAP, but pretty sure this worked regularly before already)

And in fact I would argue, this works unrelated to the ide-helper; this is just regular PHP.

**Comment by michabbb** [comment]
@mfn sure, i have found this: https://youtrack.jetbrains.com/issue/WI-30885 - and because autocomplete (in latest EAP) is not working for me, i was sure that´s because of this old bug. but when it´s working for u, it´s great 😁 which version are u using ???

**Comment by michabbb** [comment]
@mfn so i am doing something wrong accessing the user... maybe u can identify my problem within that screenshot:

![image](https://user-images.githubusercontent.com/3524595/95768861-491b3380-0cb7-11eb-99bd-cf746023dd82.png)

but also not working with:

![image](https://user-images.githubusercontent.com/3524595/95769006-7b2c9580-0cb7-11eb-94b7-14bd0ed7d368.png)

seems like something is buggy with my phpstorm 😢

**Comment by michabbb** [comment]
@mfn can u pease test something for me ?
when u go into the file: `\vendor\laravel\framework\src\Illuminate\Notifications\Notifiable.php`

are u able to show the usage of `RoutesNotifications` ??

![image](https://user-images.githubusercontent.com/3524595/95769319-fdb55500-0cb7-11eb-8a59-23b763197037.png)

**Comment by michabbb** [comment]
i did a "invalidate cache / restart" and ....

![image](https://user-images.githubusercontent.com/3524595/95771259-052a2d80-0cbb-11eb-942a-ad85b93103f6.png)

okay... wow... shit... 😖 

@mfn pardon, if i may ask: does this work for u without any phpdoc:

![image](https://user-images.githubusercontent.com/3524595/95771472-6b16b500-0cbb-11eb-912f-9ddf0e88399c.png)

because for me it´s only working with `/** @var kuchen_order $order */` and i am so confused right now, that i don´t know if that is "okay" or if phpstorm should be able to handle that, too - without any extras.

thanks!!

**Comment by mfn** [comment]
In your last case, without `/** … */` I would assume you don't even get `->user` autocomplete from `$order` because the IDE doesn't know that.

Interestingly, your code shows an anti-pattern:
```php
mode::where()->with()->get()->first();
```
- `->get()`will fetch _all_ matching results
- `->first()` will return the first from the _in memory collection_ ⬅️ not so good ❗ 

More idiomatic would be to simply do:
```php
mode::where()->with()->first();
```
because then internally it will use `limit`.

Of course if you know that `whereKoId()` will only match one entry all the time, it probably does not matter.

However: when you use the second approach, the IDE _does know_ you will get back a post 😄 

The issue is that the first call after `->with()` is on the query builder related classes which have proper phpdoc that they return `static`, i.e. a version of the model itself:
![image](https://user-images.githubusercontent.com/87493/95833430-e750dd00-0d3b-11eb-83a5-8aee65f0b50c.png)

If we look at the same for `->first()` of the collection class, it's just "mixed" and that's why the IDE "looses" the information. From `\Illuminate\Support\Collection::first`:
![image](https://user-images.githubusercontent.com/87493/95833520-08b1c900-0d3c-11eb-8ec9-caa486bbcd9d.png)

Neither PhpStorm nor Laravel have much in place here to support Generics, so this is a fix for another time (PhpStorm will receive support for this in the next major version AFAIK).

Something else: your custom phpdoc it not _quite right_. Technically `first()` always returns your "fact or null", so it would be rather:
```php
/** @var Model|null $yourModel */
```

HTH!

**Comment by michabbb** [comment]
wow, many many thanks for this great explanation! I learned something 😊👍
